### ISSUE TITLE
No error logging in Craft logs when emails sending fails

### ISSUE THREAD

**Issue by idawgik** [craftcms/postmark#19]
### Description

I was recently setting up Postmark for the first time with a Craft site. Every time I would attempt to test sending emails it would fail with the message `There was an error testing your email settings.` However, nothing was logged in the Craft logs, which made it difficult to troubleshoot. In my case, it was a side effect of still being in Trial Mode on Postmark combined with the email address on my admin account vs the site email address, however it was a very frustrating process trying to debug to figure out that was the case.

It would be great if this plugin could be updated so any errors in sending do get logged properly. From reading Postmarks documentation, the body content of the request will contain details on the error.

### Steps to reproduce

1. Set up new Postmark account in Trial Mode
2. Install Plugin in Craft and connect to Postmark
3. Make sure your system email and account email are on separate domains
4. Try sending test email
5. See error message and notice no entry in Craft logs

### Additional info

- Craft CMS version: Craft Solo 3.7.38
- Postmark plugin version: 2.1.0
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.28

**Comment by engram-design** [comment]
Any comment on this [PR](https://github.com/craftcms/postmark/pull/24) @brandonkelly ?

**Comment by green17** [comment]
Just hit the same problem.

**Comment by cherrykoda** [comment]
also running into this, someone added a PR though @brandonkelly

**Comment by timkelty** [comment]
Fixed by https://github.com/craftcms/postmark/pull/24

Released in [`craftcms/postmark:2.2.0`](https://github.com/craftcms/postmark/releases/tag/2.2.0)
